# Generated by Django 4.1.9 on 2023-06-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=256)),
                ('website', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('lat_lon_approx', models.BooleanField(null=True)),
                ('activities', models.TextField(blank=True)),
                ('identites', models.CharField(blank=True, max_length=100)),
                ('age_restriction', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
